### ISSUE TITLE
Chainstate: preprocess and cache microblock streams so we can query their state in-between anchored blocks

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#1617] opened 2020-05-21 21:46 UTC
The chainstate doesn't have an efficient way to answer queries against a microblock chain tip.  This is a problem, because the node will likely spend most of its time in a state where it will have one or more unconfirmed microblocks that will be confirmed by the next anchored block.  The node should present the user with the materialized view of the chain state _as if_ those microblocks were applied, because users will need to know what their current account state is in order to send more transactions in the epoch's subsequent microblocks.

Adding this won't be trivial, since the sequence of microblocks arrives cannot all be processed within a single chainstate transaction.  This means that the current functions `begin_block()` and `commit_to()` won't let us apply a sequence of microblocks to an existing anchored block -- in particular, these methods create new MARF tries, which have extra metadata in them that the miner will not have stored.

What we need instead is a way to make a long-lived `TrieRAM` that sticks around across block transactions.  If we can do this, then we can incrementally process microblocks as they arrive on the network in order to maintain an up-to-date materialized view.

We'd need to alter a few block-processing code paths to do this, however.  We'll need to make an equivalent `begin_block()` and `commit_to()` method pair for dealing with a set of open `TrieRAM`s, and we'll need a way to manage multiple open `TrieRAM`s at once (since microblocks can arrive and build upon any prior anchored block at any time).

I'm happy to take this as part of #1446, since it turns out this is _also_ necessary for mining microblocks.

**Comment by kantai** [comment] 2020-05-21 22:14
I think this should be possible while maintaining only a single "pending microblock" trie -- maintaining more than one such TrieRAM I think will lead to a lot of issues that can be avoided. The way I'd think about doing this is more or less as follows:

1. Anchor blocks continue to be mined and processed more or less the same as they are now.
2. Microblocks are _confirmed_ the same way that they are now.
3. Pending microblocks are stored in a TrieRAM than never gets committed. This can already be implemented by using `begin_block()` and rolling back the block. The ClarityBlockConnection can live as long as we want (though a ClarityInstance may only have one open block connection at a time -- I think this is a constraint we'd want to continue to enforce), and we can just continue processing sequential microblocks with the same TrieRAM. 
4. We should only ever process pending microblocks into the TrieRAM for the canonical chain tip. If the canonical chain tip changes, it could only have changed for one of two reasons:
   1. A new Stacks block has arrived, and it is now the canonical chain tip. The previous canonical chain tip cannot become the canonical chain tip ever again, the TrieRAM can be safely discarded.
   2. A Bitcoin fork has overtaken the current one. The previous canonical chain tip _could_ become the canonical chain tip again, if it's Bitcoin fork overtakes the new fork without any sortitions occurring. In this case, we should be comfortable either (a) not returning microblock data for RPC calls, or (b) simply reconstructing the pending microblock TrieRAM (since Bitcoin blocks are being mined here, they are providing a strict upper limit on the number of times this TrieRAM would need to be reconstructed).

Otherwise, I think we'd need to be _persisting_ these TrieRAMs, which I don't think we should be trying to do.

**Comment by jcnelson** [comment] 2020-05-21 22:46
Right -- what I'm effectively proposing here is a cache for pre-processed microblock state.  Your point in 4(ii)(b) is the special case where this cache has one item.  But I agree that, in general, the act of evicting one stream's TrieRAM to replace it with another is simply the act of throwing out the stale TrieRAM and re-calculating the replacement stream's TrieRAM.

I also agree that we don't need to persist these TrieRAMs.  The only point of keeping TrieRAMs around is to be able to quickly service queries against microblock chain tips.  They're soft-state.

But, I think we're going to realistically need at least two cached TrieRAMs though -- one for the microblock stream that grows off of the last sortition (which is going to be currently worked on), and one for the microblock stream that grows off of the longest chain tip (which will also realistically be worked on, concurrently).  These blocks are not guaranteed to be the same, but they'll receive concurrent updates.  As such, I think our solution here should support up to N cached TrieRAMs -- i.e. for the last N sortitions.

I don't want to structure this so we have to adaptively load or evict TrieRAMs in response to microblock arrivals.  That's just asking for thrashing attacks from network adversaries.  Instead, we'd just maintain TrieRAMs for the last N sortitions, and if you want to mine off of the N+1th sortition, you're on your own to figure out what goes into your microblocks (or, you run your own node with a high enough N).

What do you think?

**Comment by kantai** [comment] 2020-05-22 12:02
> Right -- what I'm effectively proposing here is a cache for pre-processed microblock state. Your point in 4(ii)(b) is the special case where this cache has one item. 

Yes -- I think we should implement only this case. I think caching multiple TrieRAMs adds complexity and memory usage for very limited benefit.

> one for the microblock stream that grows off of the last sortition (which is going to be currently worked on), and one for the microblock stream that grows off of the longest chain tip (which will also realistically be worked on, concurrently). 

I'm not sure why a node should grow one from the most recent sortition. A normal operating miner wouldn't be building off of that block unless it was the canonical chain tip. And a non-mining node shouldn't be growing a TrieRAM off of anything but the canonical chain tip.

> I don't want to structure this so we have to adaptively load or evict TrieRAMs in response to microblock arrivals. That's just asking for thrashing attacks from network adversaries. Instead, we'd just maintain TrieRAMs for the last N sortitions,

I think I'm not understanding the network adversary here -- the only way a set of pending microblocks could go from being "discarded" to needing to be reprocessed is due to a chain reorg on the burnchain. And each such reorg would only result in one set of pending microblocks needing to be reprocessed, meaning that a successful bitcoin reorg (which cannot be achieved without significant work) can at most cause 1 block to be reprocessed. Dealing with this case without reprocessing would not be solved by storing the last N sortitions' pending microblock state -- it requires caching state across burnchain forks.

**Comment by jcnelson** [comment] 2020-06-29 15:18
Just mirroring some data on the constraints that need to be held to which make this implementation difficult:

* None of the unconfirmed Clarity state will ever get committed
* No unconfirmed Clarity state exists once we begin to process an epoch
* All Clarity state nevertheless can be stored into the Sqlite DB (so we can keep using the underlying MarfedKV, and so there's a single record of it)
* The unconfirmed state persists across ClarityTx<'a> and ClarityBlockConnection<'a> instances (see below)
* At most one bundle of unconfirmed state (MARF data, Clarity data, etc.) exists per StacksChainState instance.
* If you instantiate multiple StacksChainStates from the same directory, they all share the same view of unconfirmed state (required because the p2p thread, the tenure thread, and the miner logic each need their own mutable instances).

**Closed** 2020-07-13 17:34 UTC
