### ISSUE TITLE
Make delimiters in curly brace syntax required

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1339] opened 2020-03-20 13:55 UTC
Currently, delimiters are treated as _optional_ in the curly brace tuple syntax. That leads to syntax such as:

```
{k1 v1 k2: v2 k3 v3,}
```

being treated as valid.

The vast majority of languages that support curly brace syntax instead require delimiters. We should match that behavior.

**Comment by njordhov** [comment] 2020-04-20 21:40
> The vast majority of languages that support curly brace syntax instead require delimiters. We should match that behavior.

Cargo-culting makes for bad language design. Other languages typically require these delimiters because it is necessary for unambigious parsing. This is not the case in Clarity due to the use of s-expressions, making these delimiters purely decorative. 

The proposals doesn't add anything new: Developers can already use colons and commas in curly brace tuple literals when it helps readability. Advising on such decorative syntactic sugar is better handled by a *linter.* The parser shouldn't add complexity and processing cycles just to enforce a stylistic preference. 

**We should trust developers in deciding how to make their code more readable** and keep these delimiters optional. Let's leave to Clarity developers to vote with their code and choose for themselves what they prefer, rather than mandate a specific style.

**Comment by kantai** [comment] 2020-04-20 22:09
Supporting multiple syntaxes for the same syntactic sugar is a bad idea and leads to complications both in describing the language's syntax and in learning the language.

Given that, it is preferable to support the syntax that the majority of languages and programmers are most familiar with -- brace structures with colons and commas.

**Comment by jcnelson** [comment] 2020-04-20 22:12
> We should trust developers in deciding how to make their code more readable and keep these delimiters optional. Let's leave to Clarity developers to vote with their code and choose for themselves what they prefer, rather than mandate a specific style.

Seconding @kantai.  Clarity is a language for smart contracts -- programs that are not only trusted to manage a user's valuable digital assets, but also can never be upgraded once deployed.  It should be entirely unambiguous to _users_ what the program is going to do.  Supporting multiple ways to express the same concept is anathema to this.

**Comment by njordhov** [comment] 2020-04-20 23:27
> Supporting multiple syntaxes for the same syntactic sugar is a bad idea

These are hardly multiple syntaxes, but a single syntax for literal tuples, expressed by a simple production rule with optional delimiters:

( **symbol** `:`? **expression** `,`? )+

For comparison, here is the production rule for the tuple syntax with mandatory delimiters:

( **symbol** `:` **expression** `,` )* ( **symbol** `:` **expression** `,`? )

The added complexity of the latter is reflected in the implementation.

> it is preferable to support the syntax that the majority of languages and programmers are most familiar with

The syntax with optional delimiters already supports this syntax, while allowing Clarity developers to judiciously skip delimiters for readability.

> It should be entirely unambiguous to both users and developers what the program is going to do.

The syntax with optional delimiters is already entirely unambiguous. Neither developers nor the parser require these delimiters to determine what the program is going to do; They're practically like whitespace, expressing nothing significant. 

Actually, the PR also mandates specific use of *whitespace* in tuple literals. **This should all be left to a linter** allowing developers to make their own decisions about stylistic preferences while keeping the parser simpler and faster.

**Comment by jcnelson** [comment] 2020-04-20 23:54
> The syntax with optional delimiters is already entirely unambiguous.

Two logically equivalent but syntactically different representations imposes a higher cognitive overhead than one.  We are trying to minimize cognitive overhead for _other people_ who have to read your code.

> This should all be left to a linter allowing developers to make their own decisions about stylistic preferences

Within the context of smart contract languages, developer convenience can _always_ be sacrificed if doing so makes the code easier for other people to understand.  The need to minimize this cognitive overhead comes from the high-stakes nature of programming smart contracts: it is imperative that people who use them understand what your code will do _before_ running it, or trusting it with their digital assets.

Also, if I could force all Clarity developers to use the same coding style and conventions, I would.

> while keeping the parser simpler and faster.

A parser that supports two different representations requires _strictly more code_ than a parser that supports one.

**Comment by njordhov** [comment] 2020-04-21 05:09
@jcnelson Thank you for clarifying that third party comprehensibility of the contracts trumps Clarity developer experience. An immediate insight is that Clarity is better considered a transpilation target than a potentially elegant contract language.

While [SIP 002](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-002-smart-contract-language.md#library-support-and-syntactic-sugar) discusses how to improve the developer experience, it doesn't make it clear that the priority is that the code is easier for other people to understand. Perhaps there should be a section clarifying this issue.

> Also, if I could force all Clarity developers to use the same coding style and conventions, I would.

You can, kind of. Clarity already have a canonical format: The symbolic syntax. Just pretty-print from this intermediate representation in AST to get a uniform s-expression based style. To validate that a source contract is in this format, pretty-print a parsed contract from its symbolic representation and compare to the contract character source.

**Comment by njordhov** [comment] 2020-04-21 05:12
> A parser that supports two different representations requires strictly more code than a parser that supports one. @jcnelson

Sure, but as explained earlier, there aren't *two representations* but a single production rule with optional delimiters:
( **symbol** `:`? **expression** `,`? )+

It might not be intuitive, but the way the parser is implemented to iterate over tokens, it is simpler to parse the production rule with optional delimiters than the one with mandatory delimiters. The reason is that the latter requires more state management to validate that the delimiters are in the correct places. Anyway...

**Comment by njordhov** [comment] 2020-04-21 07:21
Updated #1336 in accordance with the priorities. Will review other issues/proposals accordingly.

**Comment by njordhov** [comment] 2020-04-21 21:34
> Supporting multiple ways to express the same concept is anathema to this goal.

@jcnelson Clarity now indeed has two ways to express the tuple concept: Literals with curly braces, and the original explicit tuples using s-expressions. Is that your concern?

**Comment by jcnelson** [comment] 2020-04-23 01:22
> An immediate insight is that Clarity is better considered a transpilation target than a potentially elegant contract language.

This is again at odds with the goals of Clarity.  The code that hits the blockchain should be the code that you wrote yourself.  One of the key reasons the Stacks blockchain stores the source code on-chain, instead of a compiled binary or intermediate representation, is to ensure that the code other people read reflects your intentions as closely as possible.  Transforming your code into an alternative representation makes this difficult -- for example, how would someone else know whether or not a bug in your contract was due to your mistake, or due to the compiler (or transpiler)'s mistake?

> Clarity now indeed has two ways to express the tuple concept: Literals with curly braces, and the original explicit tuples using s-expressions. Should we be concerned?

I'm strongly of the opinion that we should support only one (cc @kantai).

**Comment by njordhov** [comment] 2020-04-25 20:03
> This is again at odds with the goals of Clarity. The code that hits the blockchain should be the code that you wrote yourself. 

I argue this should be reconsidered. Rather than expose the original contract source code from developers, it is preferable to keep the contract in a canonical format optimized for effective and reliable auditing.

> One of the key reasons the Stacks blockchain stores the source code on-chain, instead of a compiled binary or intermediate representation, is to ensure that the code other people read reflects your intentions as closely as possible. 

What matters to people using a contract isn't the presumed _intentions_ of the developer, but being able to audit how the contract actually will compute. 

What Clarity offers is a high level canonical representation that can be feasibly audited, unlike a low level representation such as binary.

The symbolic representation in AST is more authoritative for the actual computation, and can be used to generate a canonical representation of the contract code for auditing.

A practical benefit is that the Clarity parser doesn't have to be strict but instead can be *robust*, conservative in what it generates as canonical while liberal in what it accepts as contract code. This opens for a simpler, faster parser without sacrificing safety. It also opens for a more flexible, developer friendly Clarity that is a superset of the canonical Clarity hitting the blockchain.

> Transforming your code into an alternative representation makes this difficult -- for example, how would someone else know whether or not a bug in your contract was due to your mistake, or due to the compiler (or transpiler)'s mistake?

They can just audit the canonical contract reflecting the code after parsing. Today, they'd have to trust that the Clarity parser is bug-free, or consider the implementation authoritative and accept that mistakes in AST aren't actually bugs but features.

**Comment by jcnelson** [comment] 2020-04-25 22:46
> What matters to people using a contract isn't the presumed intentions of the developer, but being able to audit how the contract actually will compute.

On the contrary, the developer's intentions are exactly what you need to know in order to determine whether or not a behavior is a bug in the first place.  The AST will tell you the code's behaviors, but the developer's intentions will tell you whether or not the behaviors are desired.

The reason establishing developer intent is important in blockchain programming is that it helps identify solutions to catastrophic problems that may arise in the future.  For example, suppose there was a DAO-like event on the Stacks blockchain, where a lot of people deposited lots of STX into a popular smart contract, only for someone to later withdraw all the STX.  Is this behavior a bug, and if so, is it a bug in the smart contract or the blockchain itself?  If it's not a bug, then no action should be taken -- users should have known what they were signing up for.  If instead it's a bug in the smart contract, then this withdrawing behavior constitutes theft and law enforcement agencies should pursue the thief.  If it's a bug in the blockchain (i.e. the Clarity VM's design allowed the contract to do something undesirable), then we should consider executing an emergency hard fork and a chain roll-back to "undo" the STX transfer and prevent such behaviors going forward.  But regardless of which action is taken, the right way to handle undesirable program behavior depends on knowing what was _supposed to happen_.  This can only be determined by knowing what the developer intended -- the AST alone won't tell you this.

Therefore, we should encourage developers to convey their intentions as much as possible in the code the write, and we should encourage them to write code directly in the blockchain's native programming language.  The blockchain should preserve things like the developer's choice of whitespace, formatting, comments, variable names, etc. _as the developer wrote them_, in order to provide a record of their intentions.  Any transformations that get applied to the developer's code between when they write it and when it hits the blockchain _diminishes_ the ability for developers to convey intent, because the transformation itself may remove this information or rearrange it in unanticipated ways.

This example also illustrates why systems like Ethereum have a much harder time dealing with catastrophes like the DAO.  The DAO was "hacked" by leveraging legitimate behaviors in the EVM to mutate the contract state in such a way that the "hacker" could withdraw ETH.  But, if you are given just a copy of the compiled contract bytecode, how can you determine whether or not the withdrawal behavior is a bug?  If you do decide it was a bug, then is this a bug in the DAO, or is this a bug that the EVM allows these kinds of behaviors?  The way the Ethereum community tried to resolve this was by obtaining the DAO's original source code out-of-band, inspecting it (i.e. to determine the developers' _intentions_), and deciding that the DAO was the buggy culprit.  But, the resolution was controversial because a subset decided instead that there was no bug at all -- the code that runs on the blockchain is always necessarily correct (i.e. "code is law").  This controversial resolution, as we know, lead to another catastrophe -- a permanent chain split.

> The symbolic representation in AST is more authoritative for the actual computation than the surface syntax in the source code. It can be used to generate a canonical Clarity representation of the contract code for auditing.

This was also true of the DAO -- if you ask the Ethereum Classic community, the EVM bytecode is more authoritative than the Solidity code, because the EVM bytecode is what executes.  It is also the canonical representation of the DAO, and audits _did_ discover the problems that lead to its demise.  But per my above explanation, this only illustrates that having a separate canonical representation of the blockchain code isn't good enough for resolving bugs.

> This opens for a simpler, faster parser without sacrificing safety. It also opens for a more flexible, developer friendly Clarity that is a superset of the canonical Clarity hitting the blockchain. For example, while canonical Clarity may have mandatory delimiters in tuple literals, developer friendly Clarity can be more flexible.

Once again, developer convenience can always be sacrificed to improve the clarity of the code (no pun intended).  Having exactly one representation of a given Clarity construct minimizes the cognitive overhead required for someone else to understand what the code does.

Given my above explanation and example, I hope I have convinced you that allowing the developer's representation of the code to differ from the canonical representation of the code (i.e. the representation the blockchain executes) creates more problems than it solves.  Auditability is of course a desirable property in any smart contract programming language, and you'll get that "for free" if there is only one valid representation of a given Clarity program, but the key take-away is that auditability only tells you _what_ things the program does, not whether or not the program _should_ do them.  Seeing the developer's representation helps convey the latter.

**Comment by njordhov** [comment] 2020-05-02 04:48
> Given my above explanation and example, I hope I have convinced you that allowing the developer's representation of the code to differ from the canonical representation of the code (i.e. the representation the blockchain executes) creates more problems than it solves.

**It is up to the developers** whether their source code will be different than the canonical representation the blockchain executes. They will make their choice based on factors like programming convenience, and whether it actually is important for them that the source code can be audited to discover their intentions and determine their liability. 

It doesn't have to be a tragedy if developers prefer to transpile rather that develop directly in Clarity. Developers may prefer to write contracts in a language similar to Clarity, but without say the strict syntax requirements for spaces and delimiters, perhaps even having additional contract constructs to declare programmer's intentions. Assuming this is were we're headed, how can it best be accommodated and leveraged?

**Comment by kantai** [comment] 2020-05-02 16:11
> It is up to the developers to decide whether their source code will be different than the canonical representation the blockchain executes. They will make their choice based on factors like programming convenience, and whether it actually is important for them that the source code can be audited to discover their intentions and determine their liability. There are good reasons they will choose to transpile.

That's true, however, we do not want to actively _encourage_ transpilation. Transpiling / compiling introduces a new failure mode for blockchain ecosystems -- one in which a widely used compiler or toolchain (perhaps one even supported by the core blockchain team or foundation) exhibits a compiler bug. In this event, transactions _written to and accepted_ by the blockchain would not express the developer's intent, but there would be no clear path forward for correcting the issue (since the blockchain protocol itself did not have any bug). Because of this, we do not believe that the core protocol should be encouraging compilation or transpilation.

**Closed** 2020-05-04 14:03 UTC
