### ISSUE TITLE
[TESTNET BUG]: microblock key derivation not working as expected

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain#2049] opened 2020-11-10 22:27 UTC
## Describe the bug

After starting a miner, it joins a pre-existing STX network and syncs to the latest burnchain tip and STX tip just fine, but it does not start mining operations until a large amount of time has passed (depending on the STX height). The logs also emit the following WARNing messages:

```
WARN [1605045926.632094] [src/chainstate/stacks/db/blocks.rs:4474] [ThreadId(6)] Encountered invalid block: Invalid stacks block 578e9e2772ea55729cc14d494489d2a0da3194bf/565ecf8e66aa840e5aa796e9c835bbfa114c62c7880926bb8a07450ce01020ff -- already used microblock pubkey hash 2215229e86136fefeaa254273b1f0d150daa7645
WARN [1605046028.992105] [src/chainstate/stacks/db/blocks.rs:4474] [ThreadId(6)] Encountered invalid block: Invalid stacks block a5003e2351e9f136d29d60f5954f2c24f576fcab/12c051ca6974e3e2842b6f4af2297c564344419e1c21846ea1fbb43d3bf685c3 -- already used microblock pubkey hash e74aa54918ad8d5ae6dd1fe569b1d47ad114ff6d
WARN [1605046165.423254] [src/chainstate/stacks/db/blocks.rs:4474] [ThreadId(6)] Encountered invalid block: Invalid stacks block 951278dc8633c5d36f27a70296221842a24b0ce1/3dacc68a79ac279eefc01de9d766150b3d29f5139555af82ea50e052bc56b0da -- already used microblock pubkey hash ee95f3f535c2acbf8160c0971383c993eb24924b
```

## Steps To Reproduce

1. Start a regtest BTC node, a krypton miner, and a krypton follower which uses the miner as a bootstrap_node. These should be the _only_ two nodes on the network.
2. Wait until the burnchain and STX chain progresses consistently to verify it's working as expected.
3. Terminate the miner, and start it back up after it has fully terminated.
4. Observe the miner syncing to the burnchain tip and STX tip.
5. Once the miner is fully synced, check the logs for the errors and record the amount of time it takes for the STX tip to progress. The burnchain tip will continue progressing at a normal rate.

## Expected behavior

The miner should resume mining operations quickly after it's finished syncing with the STX network.

## Environment

 - Used the stacks-burnchain docker image `blockstack/stacks-blockchain:v23.0.0.9-krypton-stretch`

## Additional context

After discussing this with @kantai and @lgalabru in Discord, it appears the microblock keypair is not being derived, taking into account the block height. Once the keypair was rejected 60 times (the STX tip height at the time of testing), the miner would continue on to mine block 61, and so on at a normal rate. but until then, the miner is effectively stalled.

This bug seems to occur even if the `mine_microblocks` config property is set to `false`.

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [X] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [X] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

**Comment by jcnelson** [comment] 2020-11-11 00:52
Duplicate of https://github.com/blockstack/stacks-blockchain/issues/1934.  All blocks contain microblock public key hashes, but they cannot be reused in the same fork (which is why this happens even if the node isn't mining microblocks).

**Comment by kantai** [comment] 2020-11-11 15:11
@jcnelson -- I think this issue is exactly that our stacks-node implementation _should_ do better microblock public key derivation to prevent running into this error: not that the consensus algorithm needs to change.

**Closed** 2020-11-11 15:12 UTC
Labels: bug, testnet
