### ISSUE TITLE
miner keeps burning commitment and tx fee without fully synced with current chain tip

### ISSUE THREAD

**Issue by sambit4111** [blockstack/stacks-blockchain#2364] opened 2021-01-19 18:49 UTC
**Describe the bug**
Issue is observed when stacks node miner is restarted, before even syncing to current chain tip to match with seed nodes, miner starts burning commitment fee and transaction fees.

**Steps To Reproduce**
Restart the miner, have some UTXO on the btc address so that miner starts as miner mode.

**Expected behavior**
Miner should not spend commitment and tx fee until fully synced with current chain tip to avoid loss of funds to miners.

**Environment (please complete the following information):**
 - OS: Any
 - Rust version - 1.49.0
 - Version of the appropriate binary / software package - 2.0.2

**Additional context**
NA

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.
NA

**Comment by diwakergupta** [comment] 2021-01-19 19:00
@sambit4111 can you please include some more details? Right now the issue doesn't have sufficient details to debug this further. DEBUG logs, relevant transaction IDs (BTC commitments for instance) etc.

**Comment by diwakergupta** [comment] 2021-01-19 19:03
Also include your config file (omit seed or any other sensitive details), thanks!

**Comment by sambit4111** [comment] 2021-01-19 20:44
DEBUG logs are not enabled as it grows very fast in size and also presumably slows down CPU, few times it has been highlighted in discord that slow CPU might be causing transaction delays, that's the reason DEBUG logs are not available.
BTC transaction IDs are as follows

https://www.blockchain.com/btc/tx/61073778866d40982f1576275359271750cee68bba3e53504377da004dbd3715
https://www.blockchain.com/btc/tx/c4bf08a2bb3b6aa4d95adac6fcafb9803edf6010a730990bae3fd923d5152d27

toml file -

[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd48836408d9cf437344b63516@seed-1.mainnet.stacks.co:20444,03652212ea76be0ed4cd83a25c06e57819993029a7b9999f7d63c36340b34a4e62@seed-2.mainnet.stacks.co:20444"

# Enter your private key here
seed = "YOUR-PRIVATE-KEY"
local_peer_seed = "YOUR-PRIVATE-KEY"
miner = true

[burnchain]
chain = "bitcoin"
mode = "mainnet"
satoshis_per_byte = 212
burn_fee_cap = 25052
peer_host = "127.0.0.1"
username = "bitcoind-user"
password = "bitcoind-pwd"
rpc_port = 8332
peer_port = 8333

[connection_options]
public_ip_address = "your_public_ip_address:20444"
download_interval = 60
walk_interval = 30

**Comment by diwakergupta** [comment] 2021-01-20 03:11
> DEBUG logs are not enabled as it grows very fast in size and also presumably slows down CPU, few times it has been highlighted in discord that slow CPU might be causing transaction delays, that's the reason DEBUG logs are not available.

It won't be possible to debug this without debug logs. FWIW Hiro PBC, Stacks Foundation and many others run nodes with debug logs enabled, so I would not worry about CPU usage. You can rotate & compress the logs to keep file size manageable.

**Comment by MaksimalistT** [comment] 2021-01-20 15:32
I've experienced similar problem
miner was running normally then begin lagging points 6 in stacks_tip_height from stacks_tip_height on http://seed-0.mainnet.stacks.co:20443/v2/info
it took about 4-6 transaction for miner to catch up, during this time it continued to mine blocks, generate Tx and burn BTC
is it expected behaviour or not?

**Comment by kantai** [comment] 2021-01-21 18:47
Some of this behavior is expected, and should be considered normal -- blockchain miners _should_ continue to mine if there are missing blocks (this ensures a liveness property of the network).

However, mining during startup for a node is usually undesirable behavior, and should be relatively easy to patch in the `stacks-node` implementation.

**Comment by MaksimalistT** [comment] 2021-01-21 21:34
>However, mining during startup for a node is usually undesirable behavior, and should be relatively easy to patch in the stacks-node implementation.
Can you fix it?

**Comment by kantai** [comment] 2021-01-21 22:31
PR #2370 implements this.

**Comment by jcnelson** [comment] 2021-02-09 16:12
Looks like this was fixed in #2370.

**Closed by jcnelson** 2021-02-09 16:12 UTC
