### ISSUE TITLE
Epoch switch: gate access to the default cost functions

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2624] opened 2021-04-26 04:55 UTC
Because the cost functions are likely to change in 2.1 (#2623), we'll need to make sure that the cost-tracking logic loads the appropriate cost functions at the right epoch.

**Comment by jcnelson** [comment] 2021-04-26 15:40
One possibility: have the epoch-switch logic "vote in" the new cost functions, so we don't have to add gating in Rust.

**Comment by pavitthrap** [comment] 2021-11-08 05:59
Dupe of next-cost issue #2874. 

Implemented in #2888.

**Closed by pavitthrap** 2021-11-08 05:59 UTC
Labels: consensus-critical, stacks-2.1
