### ISSUE TITLE
Unable to sync burnchain: Invalid argument (os error 22)

### ISSUE THREAD

**Issue by Trudko** [blockstack/stacks-blockchain#1484] opened 2020-04-23 21:19 UTC
**Describe the bug**
Node has crashed

**Steps To Reproduce**

1. Followed instructions from https://docs.blockstack.org/core/smart/neon-node.html
2. Cloned repo
3. Updated testnet/follower-conf.toml
4. Created optimized binary
5. run ./target/release/stacks-testnet ./testnet/follower-conf.toml

**Expected behavior**

**Environment (please complete the following information):**
 - MacOS Catalina 10.15.4
 - rustc 1.42.0 
 - branch master, commit 77418c47809189621bc38f39f80d6db8ad2bbc32

**Additional context**
logs
```
INFO [1587673169.258] [src/net/relay.rs:740] Processing newly received blocks: 1
INFO [1587673176.294] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 366ca34fc0266ccf3faffcaa454246c2a6a7858ec44edbc2ed9bbba36c1ca2bb
INFO [1587673182.331] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 4387b0abe104f4cf7cffbc12032b6c55a94acb4ec4fc06747b33856cd2601763
INFO [1587673188.301] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 53aed5323328e9545d5a5f12c5746ffb9382e2c2a2c641a7a08a6f0561cd8c42
INFO [1587673196.383] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 63e2394f8fdd104d6e1b2b42d7003cebca31c08fe3beb2fc702f25e20792d03a
INFO [1587673202.716] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 4b9bc72ace35c3db9dee2855d9e9ac1b227d3c194a6b3ab2099672dc969de112
INFO [1587673209.864] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 68be6bc332f5cc690495312a90c460daa15b61e53a33c0a08bfc65bbd4779349
INFO [1587673216.735] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 0e32d92ae2d73274addf055313f771630cfc8b07d228732980456e8fdc97d61f
INFO [1587673223.981] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 6645dc8cbc3e684107f72e5871c02174767763fff75f4b42b9419dd97bc745c0
INFO [1587673230.980] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 79bc731c56df81821b5c318d94806d82c40e63822c8b8dd4608282bb860f2923
WARN [1587673235.679] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 6.424919898537172 sec...
INFO [1587673237.834] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 4e818f57c2f90a93cfbb06a716e69297460f1a2f5b966480b7682b41cb248cd9
WARN [1587673242.009] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 15.876776160903074 sec...
WARN [1587673270.971] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.5173140841753527 sec...
WARN [1587673277.743] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.2945128857077344 sec...
INFO [1587673277.787] [src/net/relay.rs:740] Processing newly received blocks: 6
WARN [1587673283.910] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.4133508283615406 sec...
WARN [1587673298.381] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.1116167949738402 sec...
WARN [1587673302.749] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.864911032344531 sec...
INFO [1587673305.076] [src/net/relay.rs:740] Processing newly received blocks: 6
WARN [1587673305.093] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 6.783110206734448 sec...
WARN [1587673311.428] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 18.721480608233115 sec...
WARN [1587673333.558] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.62967783707979 sec...
WARN [1587673340.897] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.4278682643470813 sec...
WARN [1587673346.623] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.9433786620117592 sec...
WARN [1587673353.716] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.11337794697733 sec...
WARN [1587673360.802] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.750526902740294 sec...
WARN [1587673366.841] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.6014505178152456 sec...
INFO [1587673371.564] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 73d7594c13b40fa4d8167d69efa76340eed84bc9340b049e814a40b3ab632145
INFO [1587673379.076] [src/net/p2p.rs:1769] Peer facade01+80000000://V4(35.245.47.179:20444) already known to have blocks for 4fe0326a58bee6fbf844511205e475848bb51a084221e4b43897a43539aa57d1
INFO [1587673379.554] [src/net/relay.rs:740] Processing newly received blocks: 1
WARN [1587673380.446] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.6529908501317765 sec...
INFO [1587673381.974] [src/net/chat.rs:1067] convo:id=3,outbound=true,peer=facade01+80000000://V4(35.245.47.179:20444): failed to recv on P2P conversation: PermanentlyDrained
INFO [1587673381.974] [src/net/p2p.rs:1083] Could not sign for peer facade01+80000000://V4(35.245.47.179:20444): not connected
WARN [1587673381.974] [src/net/relay.rs:981] local.80000000://V4(127.0.0.1:10001): Failed to sign for facade01+80000000://V4(35.245.47.179:20444): PeerNotConnected
WARN [1587673398.383] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.676685260581896 sec...
WARN [1587673415.724] [src/net/p2p.rs:934] Failed to get peer address of TcpStream { addr: V4(192.168.1.191:52322), fd: 40 }: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
ERROR [1587673437.457] [src/burnchains/bitcoin/network.rs:237] Failed to connect to peer 35.245.47.179:18444: connection to peer could not be (re-)established
WARN [1587673437.457] [src/burnchains/bitcoin/network.rs:247] Connection broken; retrying in 2.9716592714693038 sec...
WARN [1587673439.897] [src/burnchains/burnchain.rs:794] Detected burnchain reorg at height 1758 (< 1773). Re-sync'ing...
ERROR [1587673439.898] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid argument (os error 22)
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by duncandean** [comment] 2020-04-23 21:23
Experienced the same crash at the same commit on master.

**Comment by Trudko** [comment] 2020-04-24 06:08
Per @diwakergupta should be fixed

**Comment by jcnelson** [comment] 2020-04-24 17:42
Thanks for the debug logs!  I currently suspect that what happened is the Neon bitcoin controller crashed and rebooted, which triggerred a deep Bitcoin reorg from the perspective of your node, which in turn was not handled appropriately.

**Comment by diwakergupta** [comment] 2020-04-27 15:22
Likely dup of #1488

**Comment by diwakergupta** [comment] 2020-04-27 21:06
Duplicate of #1488

**Closed by diwakergupta** 2020-04-27 21:06 UTC
