### ISSUE TITLE
Node crash - Failed to recv on P2P conversation: PermanentlyDrained

### ISSUE THREAD

**Issue by Trudko** [blockstack/stacks-blockchain#1486] opened 2020-04-24 08:07 UTC
**Describe the bug**
Node has crashed

**Steps To Reproduce**

1. Followed instructions from https://docs.blockstack.org/core/smart/neon-node.html
2. Cloned repo
4. Created optimized binary
5. Run RUST_BACKTRACE=1 ./stacks-node neon

**Expected behavior**
Node to run

**Environment (please complete the following information):**
 - MacOS Catalina 10.15.4
 - rustc 1.42.0 
 - branch master, commit 6356b41e0e8e7115204cac43450ff56ea3ceec51

**Additional context**
logs
```
INFO [1587714924.731] [src/net/relay.rs:752] Processing newly received blocks: 3
INFO [1587714939.298] [src/net/relay.rs:752] Processing newly received blocks: 2
INFO [1587714942.740] [src/net/chat.rs:1067] convo:id=3,outbound=true,peer=facade01+80000000://V4(35.245.47.179:20444): failed to recv on P2P conversation: PermanentlyDrained
INFO [1587714942.741] [src/net/p2p.rs:449] No open socket for 3
ERROR [1587714949.691] [src/burnchains/bitcoin/spv.rs:152] bits mismatch at block 2016 of /tmp/stacks-testnet-9cf6667c7ed6d8c4/burnchain/spv-headers.dat (offset 0 interval 1 of 1-2): 545259519 != 486604799
ERROR [1587714949.691] [src/burnchains/bitcoin/spv.rs:257] Received headers with bad target or difficulty
WARN [1587714949.691] [src/burnchains/bitcoin/indexer.rs:414] Unhandled error InvalidPoW
ERROR [1587714949.691] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid proof of work
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: serde_json::number::Number::unexpected
  12: stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestController::receive_blocks
             at testnet/src/burnchains/bitcoin_regtest_controller.rs:139
  13: <stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestController as stacks_node::burnchains::BurnchainController>::sync
             at testnet/src/burnchains/bitcoin_regtest_controller.rs:516
  14: stacks_node::run_loop::neon::RunLoop::start
             at testnet/src/run_loop/neon.rs:70
  15: stacks_node::main
             at testnet/src/main.rs:77
  16: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  20: std::panicking::try
             at src/libstd/panicking.rs:281
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  24: stacks_node::print_version
```

**Comment by diwakergupta** [comment] 2020-04-24 13:18
I think the PermanentlyDrained log is spurious. This seems like the more critical error:

```
ERROR [1587714949.691] [src/burnchains/bitcoin/spv.rs:152] bits mismatch at block 2016 of /tmp/stacks-testnet-9cf6667c7ed6d8c4/burnchain/spv-headers.dat (offset 0 interval 1 of 1-2): 545259519 != 486604799
ERROR [1587714949.691] [src/burnchains/bitcoin/spv.rs:257] Received headers with bad target or difficulty
WARN [1587714949.691] [src/burnchains/bitcoin/indexer.rs:414] Unhandled error InvalidPoW
ERROR [1587714949.691] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid proof of work
```

**Comment by jcnelson** [comment] 2020-04-24 17:40
I think that's a dup of #1488.

The `PermanentlyDrained` entry just means the remote peer disconnected.  Not alarming by itself, but the fact that both the disconnect and SPV error happened at the same time suggests to me that the remote Neon node rebooted, and restarted its Bitcoin node.

**Comment by diwakergupta** [comment] 2020-04-27 20:58
Duplicate of #1488

**Closed by diwakergupta** 2020-04-27 20:58 UTC
Labels: bug, testnet
