### ISSUE TITLE
[TESTNET BUG] Krypton, master:c176dda+

### ISSUE THREAD

**Issue by vawj** [blockstack/stacks-blockchain#2226] opened 2020-12-29 11:18 UTC
## Describe the bug

Not sure if the issue still persists on Xenon, but for sure it happened for me on Krypton, I have included a stack trace.

## Steps To Reproduce

Can't find an easy way to reproduce

## Expected behavior

Ideally `stacks-node` shouldn't panic in this situation

## Environment

 - `OSX`
 - `rustc 1.48.0 (7eac88abb 2020-11-16)`
 - `stacks-node 0.1.0 => 23.0.0.0 (master:c176dda+, release build, macos [x86_64])`

## Additional context
```
INFO [1609236697.859540] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://44.234.64.128:20444 (UrlString("http://0.0.0.0:20443")) does not actually have block 6291 indexed at xxxxxx (xxxxxxx)
INFO [1609236698.264163] [src/net/relay.rs:1002] [ThreadId(7)] Processing newly received blocks: 4
ERRO [1609236698.417138] [src/vm/database/sqlite.rs:46] [ThreadId(6)] Failed to insert/replace (xxxxx): SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
Process abort due to thread panic
INFO [1609236698.418856] [src/chainstate/stacks/miner.rs:673] [ThreadId(7)] Miner: mined anchored block xxxx with 1 txs, parent block xxxxx, state root = xxxxx
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: stacks_node::main::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: std::panicking::begin_panic
   7: blockstack_lib::vm::database::sqlite::SqliteConnection::put
   8: <blockstack_lib::vm::database::marf::MarfedKV as blockstack_lib::vm::database::marf::ClarityBackingStore>::put_all
   9: blockstack_lib::vm::database::key_value_wrapper::RollbackWrapper::commit
  10: blockstack_lib::vm::clarity::ClarityTransactionConnection::commit
  11: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction
  12: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_next_staging_block
  13: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_blocks
  14: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U>::process_ready_blocks
  15: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider>::run
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: std::sys::unix::thread::Thread::new::thread_start
  19: __pthread_start

Dumping core for pid 17579
```

----

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by diwakergupta** [comment] 2020-12-29 13:40
Duplicate of #1939 , already fixed.

**Closed by diwakergupta** 2020-12-29 13:40 UTC
Labels: bug, testnet
