### ISSUE TITLE
[TESTNET BUG] Mining node panic, cexits and Linux machine collapses

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/stacks-blockchain#2018] opened 2020-10-30 16:08 UTC
## Steps To Reproduce
Running the miner and suddenly collapses 

Please provide detailed instructions (e.g. command line invocation with parameters) to reproduce the behavior.

## Environment

 - OS: [e.g. Ubuntu / Debian] Ubuntu 16.04
 - Rust version 1.45.2
 - Output of `stacks-node version` stacks-node 0.1.0 => 23.0.0.0 (master:cb75c8f, release build, linux [x86_64])

## Additional context

Please include any relevant stack traces, error messages and logs.

INFO [1604011023.000430] [testnet/stacks-node/src/neon_node.rs:1117] [ThreadId(1)] Received burnchain block #2710 including block_commit_op - mx2uds6sgnn9znABQ6iDSSmXY9K5D4SHF9 (fecb0dda5065d4a99e44b
464cf250ffd1e6185244e0e8bdc6b2fb30078244516)
INFO [1604011023.000595] [testnet/stacks-node/src/neon_node.rs:753] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1604011028.247684] [src/chainstate/stacks/miner.rs:672] [ThreadId(7)] Miner: mined anchored block 75d8b5bb1481c071b530c855e0ebfe401cc8c4ba9d8de173dfe67bf0540cc9ca with 1 txs, parent block 59885
559c44e8a536e372d874c67364e3c6e706ee0fbb6dbea27440b2efd39a6, state root = 2e3b3d43ba0a4a9108e191ff1251203b48d0f5e942e382fb00ac962fdfd601a6
INFO [1604011028.584863] [testnet/stacks-node/src/neon_node.rs:1024] [ThreadId(7)] Stacks block assembled: 75d8b5bb1481c071b530c855e0ebfe401cc8c4ba9d8de173dfe67bf0540cc9ca, with 1 txs, attempt 1
ERRO [1604011029.249874] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:596] [ThreadId(7)] Total burn fee not enough for number of outputs
INFO [1604011055.004553] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://V4(178.79.138.62:20444) (UrlString("http://0.0.0.0:20443")) does not actually have block 458 index
ed at 544730916dd7fc540542a9a79f5d7f363ef34e0b1b6a387a514549debcf127ce (0af379ce04d39d6f7941b6b66d9458f8ef9be0c3)
INFO [1604011055.004574] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://V4(139.162.204.44:20444) (UrlString("http://0.0.0.0:20443")) does not actually have block 383 inde
xed at 3a38c997512cb2dcdafffa3b424305e525b07160b064ec942d4c027938e5f4ea (f63cfefe16be922b380e78b7585e7777fe259ee6)
INFO [1604011055.004595] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://V4(178.79.138.62:20444) (UrlString("http://0.0.0.0:20443")) does not actually have block 432 index
ed at 1fa8bc52f209e2ec63ebd7fa8ebbe7bda4c29c94afbcab0366f2785fc538cb85 (359bf012728355702cedf45a5a28c8ceb006e220)
INFO [1604011055.004601] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://V4(139.162.204.44:20444) (UrlString("http://0.0.0.0:20443")) does not actually have block 411 inde
xed at 66f5fbe20d5a7fcdbb3369e54fea73d7b99587c0bc691b0fcdc611941cebacae (c2da26b8151ad03c81f0b4bd7b4546884cbbf32b)
INFO [1604011058.610581] [testnet/stacks-node/src/neon_node.rs:753] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1604011065.193715] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://V4(178.79.138.62:20444) (UrlString("http://0.0.0.0:20443")) does not actually have block 427 index
ed at c16b7d9320472b3a6ca2124162e3a489c3dbd6222b33493c6eaaa5ff852a9afb (46bbfe98157337f3d23c092821f4faead21de013)
INFO [1604011065.193735] [src/net/download.rs:467] [ThreadId(8)] Remote neighbor facade01+80000000://V4(178.79.138.62:20444) (UrlString("http://0.0.0.0:20443")) does not actually have block 383 index
ed at 3a38c997512cb2dcdafffa3b424305e525b07160b064ec942d4c027938e5f4ea (f63cfefe16be922b380e78b7585e7777fe259ee6)
INFO [1604011094.178984] [testnet/stacks-node/src/neon_node.rs:753] [ThreadId(1)] Sleeping 5000 before issuing tenure
INFO [1604011096.870395] [src/net/relay.rs:997] [ThreadId(7)] Processing newly received blocks: 4
ERRO [1604011100.611402] [src/vm/database/sqlite.rs:46] [ThreadId(6)] Failed to insert/replace (c02befcbaac6d7edaf4bfb43007afad972a82596fadb1bcbe1c5a0c19f18cf960000000000000000,0000000000000000000000
145f680b00000000000000000000000000000000000000000000000000): SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
Process abort due to thread panic
   0: stacks_node::main::{{closure}}
             at stacks-blockchain/testnet/stacks-node/src/main.rs:56
   1: std::panicking::rust_panic_with_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:490
   2: std::panicking::begin_panic
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:410
   3: blockstack_lib::vm::database::sqlite::sqlite_put
             at stacks-blockchain/src/vm/database/sqlite.rs:47
      blockstack_lib::vm::database::sqlite::SqliteConnection::put
             at stacks-blockchain/src/vm/database/sqlite.rs:79
   4: <blockstack_lib::vm::database::marf::MarfedKV as blockstack_lib::vm::database::marf::ClarityBackingStore>::put_all
             at stacks-blockchain/src/vm/database/marf.rs:522
   5: blockstack_lib::vm::database::key_value_wrapper::RollbackWrapper::commit
             at stacks-blockchain/src/vm/database/key_value_wrapper.rs:246
   6: blockstack_lib::vm::clarity::ClarityTransactionConnection::commit
             at stacks-blockchain/src/vm/clarity.rs:851
   7: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction
             at stacks-blockchain/src/chainstate/stacks/db/transactions.rs:882
   8: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_block_transactions
             at stacks-blockchain/src/chainstate/stacks/db/blocks.rs:3676
      blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::append_block
             at stacks-blockchain/src/chainstate/stacks/db/blocks.rs:3880
      blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_next_staging_block
             at stacks-blockchain/src/chainstate/stacks/db/blocks.rs:4300
   9: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_blocks
             at stacks-blockchain/src/chainstate/stacks/db/blocks.rs:4458
  10: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U>::process_ready_blocks
             at stacks-blockchain/src/chainstate/coordinator/mod.rs:642
  11: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U>::handle_new_stacks_block
             at stacks-blockchain/src/chainstate/coordinator/mod.rs:433
      blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSe
tProvider>::run
             at stacks-blockchain/src/chainstate/coordinator/mod.rs:303
  12: stacks_node::run_loop::neon::RunLoop::start::{{closure}}
             at stacks-blockchain/testnet/stacks-node/src/run_loop/neon.rs:155
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/sys_common/backtrace.rs:130
  13: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/thread/mod.rs:475
      <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panic.rs:318
      std::panicking::try::do_call
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:297
      std::panicking::try
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/panic.rs:394
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/thread/mod.rs:474
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/ops/function.rs:232
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/liballoc/boxed.rs:1076
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/sys/unix/thread.rs:87
  15: start_thread
  16: clone

Dumping core for pid 21416

If you are encountering an issue with a smart contract, please include the smart contract code
that demonstrates the issue.

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [x] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [x] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [x] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [x] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by diwakergupta** [comment] 2020-10-30 16:46
Duplicate of #1939

**Closed by diwakergupta** 2020-10-30 16:46 UTC
Labels: bug, testnet
