### ISSUE TITLE
Miner crashed

### ISSUE THREAD

**Issue by MaksimalistT** [blockstack/stacks-blockchain#2484] opened 2021-02-27 09:24 UTC
**Describe the bug**
Crash

**Environment (please complete the following information):**
 - OS: Amazon Linux
 - Rust version: rustc 1.49.0 (e1884a8e3 2020-12-29)
 - Stacks-node 2.0.6

**Additional context**
logs attached
[crash.log](https://github.com/blockstack/stacks-blockchain/files/6054089/crash.log)

**Comment by jcnelson** [comment] 2021-02-27 17:37
Hey @MaksimalistT, thanks for the logs!

I've seen this problem before when stopping and starting the miner with the same chainstate without doing a re-sync (n.b. this won't be required in the next release).  Is this what happened here?

**Comment by MaksimalistT** [comment] 2021-02-27 19:09
No, it crashed after processing about 1200 blocks

**Comment by jcnelson** [comment] 2021-02-27 20:08
The node seems to have crashed because it tried to process Stacks block `02006dc91b18f1d6eadf909e81e8fce5894591fd56030adc5868f62a6d005083` more than once.  This is an early Stacks block, mined in Bitcoin block 666064.  Do you have earlier log data that might illuminate how your node came to believe that it was missing this block and needed to process it?

**Comment by jcnelson** [comment] 2021-03-01 16:26
Confirmed from @kantai that this can be reproduced during node boot-up by pushing blocks to it.  There may be a TOCTTOU bug in the node; will investigate further and see if I can reproduce it.

**Comment by MaksimalistT** [comment] 2021-03-02 09:38
> Do you have earlier log data that might illuminate how your node came to believe that it was missing this block and needed to process it?

nope

**Comment by jcnelson** [comment] 2021-03-04 21:56
We believe this is fixed in #2497

**Closed** 2021-03-08 16:25 UTC
