### ISSUE TITLE
Reliability improvements: tolerate empty sortitions in prepare phase 

### ISSUE THREAD

**Issue by jcnelson** [blockstack/stacks-blockchain#2621] opened 2021-04-26 04:49 UTC
When evaluating the prepare phase, allow up to 10 empty sortitions without penalizing the network quality.  That is, refine the PoX activation criterion from `F * w >= 80` to `F * w >= 80 - min(E, 10)` where `E` is the number of empty sortitions during the prepare phase.

**Comment by kantai** [comment] 2021-05-27 18:51
I think this is a duplicate of https://github.com/blockstack/stacks-blockchain/issues/2535 -- closing

**Closed by kantai** 2021-05-27 18:51 UTC
Labels: consensus-critical, stacks-2.1
