### ISSUE TITLE
[TESTNET BUG] Panic on Raspberry Pi with "database is locked"

### ISSUE THREAD

**Issue by jazbogross** [blockstack/stacks-blockchain#2016] opened 2020-10-29 20:40 UTC
## Describe the bug

Running a miner on the testnet since the 26th of October uninterrupted. On the 29th of October saw miner had stopped for unknown reason.

## Steps To Reproduce

Unknown and no log exists.

## Expected behavior

No interruption.

## Environment

testing on Raspberry Pi OS.

## Additional context

Miner crashed sometime between 10am and 5pm London time on the 29th October 2020. Last lines before stopping:

```
ERROR [1603981144.582] [src/vm/database/sqlite.rs:46] [ThreadId(6)] Failed to insert/replace (fee16acd18a8299ee75b4384d315a2c568346d7a2ac07a2b2f24fe489a7d47dd0000000000000000,00000000000000000000000719f11100000000000000000000000000000000000000000000000000): SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
Process abort due to thread panic
"Event! Hello world"
   0: backtrace::backtrace::libunwind::trace
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.50/src/backtrace/libunwind.rs:95
      backtrace::backtrace::trace_unsynchronized
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.50/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.50/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.50/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/backtrace-0.3.50/src/capture.rs:128
   4: stacks_node::main::{{closure}}
             at testnet/stacks-node/src/main.rs:52
   5: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573
   6: std::panicking::begin_panic::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:498
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
   8: std::panicking::begin_panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
   9: blockstack_lib::vm::database::sqlite::sqlite_put
             at src/vm/database/sqlite.rs:47
  10: blockstack_lib::vm::database::sqlite::SqliteConnection::put
             at src/vm/database/sqlite.rs:79
  11: <blockstack_lib::vm::database::marf::MarfedKV as blockstack_lib::vm::database::marf::ClarityBackingStore>::put_all
             at src/vm/database/marf.rs:522
  12: blockstack_lib::vm::database::key_value_wrapper::RollbackWrapper::commit
             at src/vm/database/key_value_wrapper.rs:246
  13: blockstack_lib::vm::clarity::ClarityTransactionConnection::commit
             at src/vm/clarity.rs:851
  14: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction
             at src/chainstate/stacks/db/transactions.rs:882
  15: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_block_transactions
             at src/chainstate/stacks/db/blocks.rs:3676
  16: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::append_block
             at src/chainstate/stacks/db/blocks.rs:3880
  17: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_next_staging_block
             at src/chainstate/stacks/db/blocks.rs:4300
  18: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_blocks
             at src/chainstate/stacks/db/blocks.rs:4458
  19: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U>::process_ready_blocks
             at src/chainstate/coordinator/mod.rs:642
  20: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U>::handle_new_stacks_block
             at src/chainstate/coordinator/mod.rs:433
  21: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider>::run
             at src/chainstate/coordinator/mod.rs:303
  22: stacks_node::run_loop::neon::RunLoop::start::{{closure}}
             at testnet/stacks-node/src/run_loop/neon.rs:155
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:137
  24: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:458
  25: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:308
  26: std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  27: __rust_try
  28: std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  29: std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  30: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/mod.rs:457
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
  32: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87

Dumping core for pid 1500

**Comment by diwakergupta** [comment] 2020-10-30 00:12
@jazbogross thanks. To set expectations, while we appreciate and encourage community members to test stacks-blockchain on a variety of platforms, none of the core developers build or test on Raspberry Pi, so YMMV.

Can you also include the stacks-blockchain version? Available either via `/v2/info` or by running `/path/to/stacks-node version`

**Comment by diwakergupta** [comment] 2020-10-30 00:13
@dantrevino have you experienced anything similar on your RPi setup?

**Comment by dantrevino** [comment] 2020-10-30 08:35
> @dantrevino have you experienced anything similar on your RPi setup?

I have not,  but I don't have a running recent version at the moment.  I'll fire one up on Friday.

**Comment by diwakergupta** [comment] 2020-10-30 14:24
Actually looks like a duplicate of #1939 , closing in favor of that.

**Closed by diwakergupta** 2020-10-30 14:24 UTC
Labels: bug, testnet
