### ISSUE TITLE
[TESTNET BUG] Mocknet crashes

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#2100] opened 2020-11-30 09:31 UTC
## Describe the bug

Running `cargo testnet mocknet` results in the following crash:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/stacks-node mocknet`
INFO [1606728409.034240] [src/chainstate/stacks/index/marf.rs:216] [ThreadId(1)] First-ever block 55c9861be5cff984a20ce6d99d4aa65941412889bdc665094136429b84f8c2ee, block: 55c9861be5cff984a20ce6d99d4aa65941412889bdc665094136429b84f8c2ee
INFO [1606728415.377666] [src/chainstate/stacks/index/marf.rs:216] [ThreadId(1)] First-ever block 55c9861be5cff984a20ce6d99d4aa65941412889bdc665094136429b84f8c2ee, block: 55c9861be5cff984a20ce6d99d4aa65941412889bdc665094136429b84f8c2ee
ERRO [1606728415.411697] [src/chainstate/stacks/index/storage.rs:1550] [ThreadId(1)] Not found (no file is open)
INFO [1606728415.412212] [src/chainstate/stacks/index/marf.rs:216] [ThreadId(1)] First-ever block 0000000000000000000000000000000000000000000000000000000000000000, block: 0000000000000000000000000000000000000000000000000000000000000000
INFO [1606728415.492781] [src/chainstate/burn/db/sortdb.rs:3110] [ThreadId(1)] ACCEPTED(1) leader key register a17565bb827d6466ffcbef8bc0bdd650a12afa5c6914dd00c4c8c77602660827 at 1,1
BOOTSTRAP WITH []
INFO [1606728415.506864] [src/net/db.rs:165] [ThreadId(1)] Peer's public key: 0278e76205485d026f757ae00eb3305c0484f4711c23a3259f2db256364d888fbb
DENY NEIGHBORS []
ERRO [1606728415.523027] [src/net/poll.rs:112] [ThreadId(1)] Failed to bind to 0.0.0.0:20444: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
Process abort due to thread panic
   0: stacks_node::main::{{closure}}
             at testnet/stacks-node/src/main.rs:56
   1: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   5: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   7: core::result::Result<T,E>::unwrap
             at /home/friedger/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973
   8: stacks_node::node::spawn_peer
             at testnet/stacks-node/src/node.rs:92
   9: stacks_node::node::Node::spawn_peer_server
             at testnet/stacks-node/src/node.rs:362
  10: stacks_node::run_loop::helium::RunLoop::start
             at testnet/stacks-node/src/run_loop/helium.rs:75
  11: stacks_node::main
             at testnet/stacks-node/src/main.rs:136
  12: core::ops::function::FnOnce::call_once
             at /home/friedger/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/friedger/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  14: std::rt::lang_start::{{closure}}
             at /home/friedger/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  16: std::rt::lang_start
             at /home/friedger/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  17: main
  18: __libc_start_main
  19: _start

Dumping core for pid 143108
Quit (core dumped)
```

## Expected behavior

Mocknet should start

## Environment

 - OS: Ubuntu
 - Rust version: `rustc --version`:  rustc 1.47.0 (18bf6b4f0 2020-10-07)
 - git commit: e8f8144cd48ab28f1d08d1a8e5ead13b5a6bcf58

----

If you think this is eligible for a [bug bounty](https://testnet.blockstack.org/bounties), please check the relevant boxes below:

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [x] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by diwakergupta** [comment] 2020-11-30 14:38
@friedger do you already have something running on port 20444? `[ThreadId(1)] Failed to bind to 0.0.0.0:20444: Os { code: 98, kind: AddrInUse, message: "Address already in use" }`

If so, this isn't a bug, though I'm sure we can improve the error handling in this case.

**Comment by diwakergupta** [comment] 2020-11-30 14:46
@friedger I just tried the mocknet and it works fine. I'm quite positive you had another process running on that port (perhaps a different instance of the testnet?) -- so this is working as intended and I'm going to close this issue out. Please reopen as needed.

**Closed by diwakergupta** 2020-11-30 14:46 UTC
