### ISSUE TITLE
Burnchain: Bitcoin TCP sockets should have a read timeout and a connect timeout

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#1680] opened 2020-06-16 15:34 UTC
Per discussion yesterday, we should probably set sane default socket options for both blocking and non-blocking sockets.

**Comment by jcnelson** [comment] 2020-06-16 15:46
We already do this.

**Comment by jcnelson** [comment] 2020-06-16 16:58
Sockets are instantiated and configured in two sites (possibly 3, depending on how you count [1]) in the `blockstack_lib` codebase:

* in `src/net/poll.rs`, which instantiates non-blocking sockets for both P2P and HTTP connections with other Stacks nodes
* in `src/burnchains/bitcoin/indexer.rs`, which instantiates a blocking socket connection to Bitcoin's P2P interface

We have two sites because these sockets communicate with two different networks (the Stacks network and the Bitcoin network) that have different expected behaviors, and we do so via two different protocol paradigms (non-blocking event-driven vs. blocking RPCs).  The socket configurations for these networks are substantially different, and necessitate different configuration logic.

I closed this issue because (a) we are already setting the requisite socket options in the relevant sites and (b) we cannot remove any of the current configuration sites without also increasing the code's complexity or decreasing its comprehensibility.  We're effectively already doing what this issue requests.

[1] Implicitly, sockets are also instantiated and configured within the testnet node in `testnet/stacks-node/src/event_dispatcher.rs`.  However, this is done within a 3rd-party HTTP client library (currently `reqwest`, soon to be `async-h1`, but ultimately our own in `src/net/poll.rs`), so any socket configuration will depend on what options the 3rd-party library exposes.

**Comment by kantai** [comment] 2020-06-16 17:15
> in src/burnchains/bitcoin/indexer.rs, which instantiates a blocking socket connection to Bitcoin's P2P interface

This site should add a default timeout, though.

**Comment by jcnelson** [comment] 2020-06-16 17:27
> This site should add a default timeout, though.

We should also add a connect timeout (by using `connect_timeout()`).

I'll re-open this issue under a more specific name.

**Comment by jcnelson** [comment] 2020-10-31 17:40
Fixed in #2014

**Closed by jcnelson** 2020-10-31 17:40 UTC
