### ISSUE TITLE
Neon Testnet node stopped in Ubuntu and having error verbiage

### ISSUE THREAD

**Issue by michaeljiflorida08** [blockstack/stacks-blockchain#1499] opened 2020-04-25 23:33 UTC
**Describe the bug**
somehow, after Neon Testnet node running in Ubuntu for hours, it stopped and having the following error verbiage (I didn't change config, so, it run by the default)

Error message is appended.

**Steps To Reproduce**
Commands to launch blockstack node
"git clone https://github.com/blockstack/stacks-blockchain.git
cd stacks-blockchain
cargo install --path ./testnet
stacks-node neon"

**Expected behavior**
Neon Testnet Node should keep running and communicating to peer node(s)

**Environment (please complete the following information):**
Ubuntu18.04

 - Rust version
rustc 1.42.0 (b8cedc004 2020-03-09)

**Additional context**
Error Message:
"ERROR [1587837526.114] [src/burnchains/bitcoin/spv.rs:152] bits mismatch at block 2016 of /tmp/stacks-testnet-c273a2966cadf96b/burnchain/spv-headers.dat.reorg (offset 0 interval 1 of 1-2): 545259519 != 486604799
ERROR [1587837526.115] [src/burnchains/bitcoin/spv.rs:257] Received headers with bad target or difficulty
WARN [1587837526.115] [src/burnchains/bitcoin/indexer.rs:414] Unhandled error InvalidPoW
ERROR [1587837526.115] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch headers from 2000 - 2016
ERROR [1587837526.115] [src/burnchains/burnchain.rs:794] Failed to check for reorgs from 2016
ERROR [1587837526.115] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid proof of work
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace"

**Comment by michaeljiflorida08** [comment] 2020-04-26 01:03
[logging-2020_04_25.txt](https://github.com/blockstack/stacks-blockchain/files/4534437/logging-2020_04_25.txt)

**Comment by whoabuddy** [comment] 2020-04-27 13:21
I experienced the same issue.

**Describe the bug**

Installed and started the testnet on an Ubuntu server and left it running, when I came back to the office the same error message was on my screen.

**Steps To Reproduce**

Install Ubuntu, [install dependencies](https://github.com/blockstack/docs.blockstack/issues/575), and follow the README instructions up through `stacks-node neon`.

**Expected behavior**

That it would still be running when I came back to the office!

**Environment (please complete the following information):**

- OS: Ubuntu Server 20.04 LTS
- Rust: 1.43.0 (4fb7144ed 2020-04-20)

**Additional context**

Same error as above.

**Comment by diwakergupta** [comment] 2020-04-27 15:19
Likely dup of #1488

**Comment by diwakergupta** [comment] 2020-05-04 15:07
Duplicate of #1488

**Closed by diwakergupta** 2020-05-04 15:07 UTC
