### ISSUE TITLE
stacks-node will stop handling RPC calls

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1702] opened 2020-06-30 03:03 UTC
**Describe the bug**
If a node is connected to an event observer (e.g. sidecar), and a query to that event observer returns an error, `send_payload` in `event_dispatcher` will keep repeating the query at increasingly longer intervals.  After that loop has started, other RPC calls become unresponsive (e.g. `/v2/transactions`, but probably others, that's just the one I observed), making the node unusable to deploy contracts or executing contracts, the connections hang, and in the case mentioned `parse_posttransaction` in `http.rs` never gets called when sending an RPC request (for example, deploying a contract).

The node (I was using mocknet) keeps on producing blocks, however, although not sure whether listening to peers would also be blocked.

I suppose that both pushing txs and blocks to the event listeners and RPC calls are handled by the same thread?

**Steps To Reproduce**
make the event observer return an error (status !== 200), like a bad postgres query for example after it is connected to a stacks-node.

**Expected behavior**
RPC calls should not be blocked.  In fact, I wonder whether that loop is a good idea in the first place, except when waiting for the observer to start.  I'm guessing this would also cause other event observers to stop receiving updates as well.

Let me know if you have any questions on how to reproduce this.

**Comment by diwakergupta** [comment] 2020-07-06 15:00
@psq this is the intended behavior. Will let @jcnelson or @zone117x chime in with additional context, marking as `wontfix` for now.

**Comment by psq** [comment] 2020-07-06 23:53
I'm curious to find out what the rationale is.

What this seems to imply is that the only remedy is to restart the event observers and, possibly, the node, making the node tightly coupled to its observers (intuitively, I would think the observers should not be needed for proper functioning of the node, and should not affect its ability to function properly).

It also looks like, along with not being able to be used as an endpoint to deploy and execute contracts, transfer tokens... the node would also stop relaying to other nodes, as this seems to be done in the same thread.

**Comment by diwakergupta** [comment] 2020-07-07 14:19
@psq rationale is that if a node has enabled the event dispatcher, then the consumer of those events in effect "drives" the node. Event consumers can implement buffering or drop events if they're not able to keep up with the event stream, but from the nodes point of view, any other behavior quickly becomes hard to reason about and full of edge cases.

We can into several issues in the course of developing the sidecar that led to this choice. For instance, if the sidecar is not responsive or unavailable for whatever reason, what should the node behavior be? If it drops events, the sidecar (and by proxy, the explorer) will never learn of those events, which might manifest as a data loss to someone using the explorer.

So yes, if event dispatcher is enabled, the node _is_ tightly coupled to the event consumer by design.

**Closed by diwakergupta** 2020-07-07 14:19 UTC
Labels: wontfix
